```{r, echo=FALSE}
source(file = "include/deadlines.R")
```

# Assessment Information Sheets {#AIS}

## Stage 1 Report

The assessment is due on the `r stage1_due`. 

## Stage 2 Report

The assessment is due on the `r stage2_due`. 

## MCQ

### General information

- You are required to answer a set of multiple-choice questions that relate to the course content for RM1. This includes lectures, data skills, labs and academic writing tutorials. 

- In total, this assessment is worth 5% of your final course grade. 

- The deadline for submitting the MCQ is `r MCQ_due`.

### How to do well in this assessment

- Keep up with the course content on a weekly basis.

- Complete the essential reading for each lecture.

### Common mistakes

- Not keeping up with the lecture content and reading.

- Failing to read the question carefully.

- Failing to answer all questions. 

### Why am I being assessed like this?

- Testing your knowledge of the course content helps you actively engage with the material, meaning you will learn more.

- Engaging with the material on the course will help build a strong foundation for the rest of the RM1 course and your subsequent assessments. 

## Data skills

The data skills 1 assessment is due on the `r dataskills1_due`. 

The data skills 2 assessment is due on the `r dataskills2_due`. 


