```{r, echo=FALSE}
source(file = "include/deadlines.R")
```

# Course Resources {#Resources}

## Fundamentals of Quantitative Analysis

To support this course, we have the [Fundamentals of Quantitative Analysis book](https://psyteachr.github.io/quant-fun-v2/index.html) which teaches you data skills in R, like programming basics, data wrangling and visualisation, and statistical tests. We work through chapters 1 to 12 in RM1, then you will continue with chapters 13 to 17 in RM2 in semester 2. 

## Handy workbook

An additional resource we will link to time to time is [A Handy Workbook for Research Methods & Statistics](https://psyteachr.github.io/handyworkbook/index.html). From around week 5, we will introduce you to inferential statistical tests. When you use these practically, you will use R to efficiently analyse larger amounts of data. In this book, we work through step-by-step how these statistical tests work, so you can gain a better understanding of what numbers go in, what happens to those numbers, and what numbers come out. 

## Course reading list

To support each week, there is a course reading list which is linked on the Moodle page, but you can access it by [following this link](https://rl.talis.com/3/glasgow/lists/E221C1E0-F1F5-5F70-998B-FF01BF1286E1.html). We appreciate you only have so much time each week and have other courses to complete, so the resources are labelled as essential, recommended, and further. 

Essential sources are those that we have curated to directly supplement the lecture and lab material, and you should do your best to keep up with reading these each week. 

Recommended sources are those that we think are useful and supplement the course, but you should only read them if you have time. 

Further sources are those we find interesting and provide a deeper dive if you find you really enjoy the content in this course.
