```{r, echo=FALSE}
source(file = "include/deadlines.R")
```

# Stage 2 Individual Report {#stage2-AIS}

## General information 

- The stage two individual report builds on your stage one group report, but this time you report your results and discussion. The general topic for your report is still on self-regulated learning. 

- The deadline is **`r stage2_due`**.

- This assessment is worth 50% of your final course grade. 

- You should submit a single Word document (.docx) to Moodle prior to the deadline. The submission link will open at least one week prior to the deadline and will be in the Assignment Submission section of Moodle.

## Word count and formatting

- The maximum word count for the stage two report is **`r stage2_words`** words. 

- This includes all text within the results and discussion sections including in-text citations. However, it does not include the references or any appendix items.

 - Please note that there is no 10% rule, **`r stage2_words`** words is a strict upper limit.

- Your work should be presented in a sans-serif font, e.g. Arial or Calibri, 12-point font, double-spaced with 1-inch (2.54cm) margins.

 - All citations and references should follow APA 7th edition guidelines.

## Type of assessment/structure

- The stage two group report is modeled on the second half of a [registered report](https://www.cos.io/initiatives/registered-reports). When a research team has their stage one submission approved, they go out and collect data, then write up their results and discussion. You are working with secondary data, so you will not collect any data, but you are putting your stage one plan in action and justifying any deviations from your plan.  

- Your stage two individual report will include a results and discussion section, plus references (and appendices if relevant). You will receive a template outlining the key sections and as part of the course. 

## Assessment Criteria

- Quality of the Knowledge and Research

    - Demonstrate theoretical knowledge by providing a detailed evidence-based understanding of the topic of the report.

    - Demonstrate technical knowledge by correctly reporting and interpreting the results

- Quality of the Evaluation

    - Use and show academic evidence to support all arguments and discussion.

    - Evaluate your study and how your results fit into the wider literature.

- Quality of the Academic Communication

    - Write clearly and succinctly with appropriate use of paragraphs, spelling and grammar.

    - Reference all sources and report all information in line with APA guidelines.

    - Ensure that all parts of the report have a logical structure, e.g., the results should present descriptive statistics before inferential statistics, and the discussion should follow a narrow to broad structure.

## Assessment support

- Guidance on how to write a psychology report and how to do APA referencing form part of the weekly course activities. You should consult the resources provided throughout the course to help you write your stage two report.

 - Further information about assessment criteria and feedback is available in the [Feedback Information Sheet section](#stage2-FIS).

- Additional writing and study advice, including 1-to-1 guidance is available via the [Student Learning Development (SLD) website](https://www.gla.ac.uk/myglasgow/sld/).

## How to do well in this assessment

- Meet each of the assessment criteria - use these as a checklist for your work.

- Allow time to proof-read your work before submission.

- Read peer-reviewed journal articles (preferably registered reports to see the specific approach) as these will help guide your tone and help you develop your academic writing. Remember that you can read anything for content and style. These are different mindsets when reading so go into your reading with a given purpose  - what do I want to get from this paper? - and that will help use your time more efficiently.

- Write clearly, concisely, with a professional academic tone and logical structure.

- Avoid using quotations. Rephrasing the writing in your own words and with appropriate citation is much more effective in conveying information.

- Concisely and accurately report and interpret descriptive statistics, assumptions tests, and inferential statistics. Note and justify any deviations from the stage one report.

- Present appropriate visualisations for the analyses that you conduct. 

- Interpret the results of the project in the context of the wider literature

- Demonstrate evidence of evaluation, both of the wider literature and of the current project.

- Provide a concise conclusion and an overall summary that covers each section of the report in the form of an abstract.

- Adhere to APA conventions for referencing, formatting, and the reporting of results.

## Common mistakes

- Writing that contains grammatical errors, a lack of clarity, or an informal tone. Reading published articles in comparison to scientific blogs or newspapers will greatly help get the correct tone. The key is to focus on how they are writing and phrasing differently across different media.

- Missing detail and/or unnecessary detail in the result sections.

- Failure to report the results of statistical tests according to APA convention.

- Failure to provide necessary visualisations or the inclusion of unnecessary visualisations. You do not need to provide visualisations for any assumption tests in the main report (although you can include these in the appendix).

- A lack of evaluation of the wider literature and the current project and/or a discussion of the limitations that is not supported by evidence. 

- Failure to adhere to the word limit. Part of the skill development is writing concisely.

## How is the assessment related to the lectures for this course?

- The stage two report assesses your ability to apply the concepts that you have learned about during the lectures. This includes methodology and research design, statistics, and communicating research. 

- Depending on the exact topic you choose, the project may also be related to content from your lectures on memory, learning, social psychology, and mental health and well-being. 

## Why am I being assessed like this?

- Registered reports are becoming increasingly common in psychological research and it is a process that will serve you well should you continue with research as it demonstrates a commitment to open and reproducible science.

- The stage two report allows you to address your research question using your planned methods and analyses from the stage one report. You will then put your findings in context and explore how your results were either consistent or inconsistent with past research, while noting any important limitations in your methods. 

- The stage two report will help you with your qualitative RM2 report, dissertation, and with any other written research-focused work you may conduct in the future.

## How does this relate to previous work I have completed?

- You can gain informal feedback by talking to your lab tutor, by attending student office hours, by asking questions on Teams, and by discussing papers you have read with peers and/or staff. 

- Feedback from your stage one group report may help you with justifying any deviations from your data analysis plan, in your discussion to identify limitations, and your use of technical terminology.

- Feedback on any written assignment will help with academic communication. 

## Academic Integrity

Please note that when submitting your work for assessment we accept it on the understanding that it is your own effort and work and unique to the set assignment. 

To support you in understanding what plagiarism is and in avoiding it, please read the following resources that the University provides:

-	[SRC Advice and Support](https://www.glasgowunisrc.org/advice/)

-	[Code of Student Conduct](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2023-24/feesandgeneral/studentsupportandconductmatters/reg33/) and [Plagiarism Statement](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2023-24/feesandgeneral/studentsupportandconductmatters/reg32/)

-	[Avoiding plagiarism and engage in good academic practice](https://moodle.gla.ac.uk/course/view.php?id=13038) (a Moodle course you can self-enrol in)

-	[Academic Advice in MVLS](https://www.gla.ac.uk/myglasgow/sld/writingstudyadvice/mvls/)

**University statement on AI**: The advent of free AI tools is transforming our world and offers many opportunities to help us deal with large amounts of information. While we support students in learning how to use these tools to help them study, you should not submit for assessment something generated by an AI tool as though it is your own work. Please carefully read the [University’s position on AI](https://www.gla.ac.uk/myglasgow/sld/ai/).

**Statement on groupwork**: This report is not a group work assignment, so your work must be your own individual contribution. However, as you worked closely in a small team and from common templates, we know that there may be some unavoidable similarities between team members in the results, but it should never be identical or close to identical.

## Feedback information {#stage2-FIS}

### What type of feedback will I receive for this assessment?

You will receive feedback on your attainment of the overall marking criteria (Knowledge and Research, Critical Evaluation, Academic Communication) in terms of the verbal descriptors from Schedule A and feedforward comments as to how to develop your knowledge and skills for future assignments.

Assessments are graded on the 22-point scale using the Schedule A marking criteria. There are three equally weighted Assessment Criteria (Knowledge and Research, Critical Evaluation, Academic Communication). You can find out more about Schedule A by [downloading this PDF](https://www.gla.ac.uk/media/Media_541792_smxx.pdf) but the important thing to help you interpret your feedback is the use of the verbal descriptors, i.e., the words like “excellent” and “good” used to describe different grades. You should look out for these words to help you understand how you performed on each ILO.

### Can I get more feedback?

You are more than welcome to receive additional feedback after the marking process:

- If you would like to discuss your feedback you should first contact the person that marked your assignment. However, we ask that you wait 24 hours after the release of the feedback before you do so to give you time to fully reflect on the feedback given. 

- When meeting with the person who marked your assignment, you can discuss feedback and how it relates to your overall grade to help you improve in future assignments. However, do not be worried about attending to discuss how to maintain your standard if you have done better than you expected. You are more than welcome to come discuss any aspect of your feedback or the assignment in general. 

- To help any discussion about your feedback, we would ask that you complete the reflection form available on the Moodle page and send that to the person who marked your assignment as part of the discussion, when arranging a meeting.

### How will feedback from this assessment help me in the future?

The feedback on this assessment will help you in writing future research reports, such asthe qualitative report in semester 2, your MSc dissertation, and in any future research work you conduct that requires academic writing and evidence-based evaluation.

### Who assessed my work?

The first marker for your report will be a member of the research methods team within the School of Psychology and Neuroscience.

Following University’s policy, as part of the marking procedures, the assignment marking will be moderated. The moderator will be another member of the research methods team who will moderate a range of work from across the cohort to ensure that appropriate academic standards have been applied in marking the assignments and that they have been applied consistently across the cohort of students being assessed. 

### Can I have my work regraded?

Further feedback meetings with the person who marked your assignment is purely about additional information to help you improve and is not about changing your grade or having your work regraded. That said, even if you are unhappy with your grade, your first point of contact should be to arrange an additional feedback meeting with your marker for further discussion to help explain your feedback and grade. Following this, if you still have concerns you should consult the [guidance from the SRC](https://www.glasgowunisrc.org/advice/academic/appeals/) which provides a clear explanation of the University appeals procedures. 
