```{r, echo=FALSE}
source(file = "include/deadlines.R")
```

# MCQ

## General information

- You are required to answer a set of multiple-choice questions that relate to the course content for RM1 covered in weeks 1-4. This includes lectures, data skills, labs and academic writing tutorials. 

- In total, this assessment is worth 5% of your final course grade. 

- The deadline for submitting the MCQ is **`r MCQ_due`**.

## How to do well in this assessment

- Keep up with the course content on a weekly basis.

- Complete the essential reading for each lecture.

## Common mistakes

- Not keeping up with the lecture content and reading.

- Failing to read the question carefully.

- Failing to answer all questions. 

## Why am I being assessed like this?

- Testing your knowledge of the course content helps you actively engage with the material, meaning you will learn more.

- Engaging with the material on the course will help build a strong foundation for the rest of the RM1 course and your subsequent assessments. 

## Academic Integrity

Please note that when submitting your work for assessment we accept it on the understanding that it is your own effort and work and unique to the set assignment. 

To support you in understanding what plagiarism is and in avoiding it, please read the following resources that the University provides:

-	[SRC Advice and Support](https://www.glasgowunisrc.org/advice/)

-	[Code of Student Conduct](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2023-24/feesandgeneral/studentsupportandconductmatters/reg33/) and [Plagiarism Statement](https://www.gla.ac.uk/myglasgow/apg/policies/uniregs/regulations2023-24/feesandgeneral/studentsupportandconductmatters/reg32/)

-	[Avoiding plagiarism and engage in good academic practice](https://moodle.gla.ac.uk/course/view.php?id=13038) (a Moodle course you can self-enrol in)

-	[Academic Advice in MVLS](https://www.gla.ac.uk/myglasgow/sld/writingstudyadvice/mvls/)

**University statement on AI**: The advent of free AI tools is transforming our world and offers many opportunities to help us deal with large amounts of information. While we support students in learning how to use these tools to help them study, you should not submit for assessment something generated by an AI tool as though it is your own work. Please carefully read the [University’s position on AI](https://www.gla.ac.uk/myglasgow/sld/ai/).

**Statement on groupwork**: We encourage students to form a study group and peer feedback groups. However, this assignment is not a group work assignment, so your work must be your own individual contribution. If you make a study group or a peer review group, avoid sharing your final answers.

## Feedback information

### How is this assessment graded?

The MCQ has 22 questions with each question being worth 1 point. Your grade will be converted into an alphanumeric grade on the standard 22-point scale (e.g., a score of 16 = B2). 

### What type of feedback will I receive for this assessment?

Once the quiz has closed for all students, you will be able to see which questions you got right and wrong, and what was the correct answer in addition to your overall grade. 

### Who assessed my work?

The MCQ is scored automatically within Moodle. An experienced member of staff created the quiz and it was proof read by another member of staff to ensure the scoring is accurate. 
