```{r, echo=FALSE}
source(file = "include/deadlines.R")
```

# Week 3

## Lab overview

Now you are working in your groups, we will start to build the skills and understanding that will go into your report writing. Before reading week, we will focus on the stage one group report. This means we will break down the introduction and method sections for what research has influenced your study and how you designed your study to test your research question.

This week, we are focusing on the introduction. This is the first major part of a report and usually one of the longest. The aim of a report introduction is to explain and justify the gap you identified in previous research. As we work through the broad to narrow structure, you provide a focused literature review explaining why the topic is important to study and what previous research and theory is out there. As you move through the introduction, you get more and more specific to guide the reader towards your rationale. The rationale is the purpose of your study, or what gap your study is addressing and why it is important to do so. Finally, the introduction typically ends on your research question and your hypothesis (if applicable). 

After a summary of the pre-lab reading chapter, the group element of the lab will focus on discussing where the article you found (see pre-lab tasks) might contribute to your stage one report introduction. Is it more background research or theory, or could it contribute as a key study towards your rationale? 

## Tasks to complete prior to your lab

1. Read this week's research skills chapter on [Structure of the Introduction and Rationale](#intro-rationale), and complete the activity on identifying the rationale. 

2. Using the literature searching strategies you learnt about in week 2, find **one** article that could contribute to your group's introduction section. 

## Tasks to complete after attending your lab

1. Before the deadline of `r groupagreement_due`, submit your individual copy of the group work agreement you developed and agreed on in your group. 

2. If you are still discussing your variable pair, aim to finalise your group decision before the end of week 3. 

## Next week 

Next week, we will focus more on the skill elements that contribute to your introduction and report. The lab and pre-lab reading will explore academic writing, including tone, paragraph structure, and citation placement. 
