# Week 10

## Lab overview

You have made it to the final week! In the final lab of the semester, we are finishing off with two final components of an empirical quantitative report. 

First, we will explore limitations in greater detail. These are included in the discussion and inform the reader about features of your study that may threaten the validity of your findings and how these features affect how much confidence you have in your findings/conclusions. We introduced the idea of limitations to you last week, but it takes time and experience to develop a good sense of what specific limitations affect your study. So, this week, we introduce you to a framework to help think about different types of limitations and hopefully inspire you to think about what limitations are present in your work. 

Second, we will end on the final component of a report: the abstract. You have probably read enough articles by now to recognise you read the abstract first. After the title, its typically the first thing you read and provides a little overview of your report. If you are conducting a literature review, you might read the abstract and decide whether the full article is worth reading or not. So, an effective abstract provides a summary of your whole report, condensed into a paragraph. 

## Tasks to complete prior to your lab

1. Read the [Identifying Limitations and Structure of the Abstract](#limitations_abstract) chapter. 

2. Complete the [abstract comparison task](#abstract-task).  

## Tasks to complete after attending your lab

1. Submit your data skills 2 assignment prior to the deadline. 

2. Write a bullet point plan of your discussion and start working on the draft of your stage two report. 

## Next week

We have no more labs or lectures this semester! We said it last week, but this is now the time to reflect and think about how far you have come in the course. You must learn many skills for research methods with very little time, so we do hope you are proud of yourselves. 

There are no labs or lectures, so you have the core components to write your stage two report. You have approximately two weeks to just focus on your remaining assignments prior to the Christmas break. Do not worry, we all do not just disappear now. We will have our office hours and you still have the Teams channel to post your questions to. 

## Abstract comparison task{#abstract-task}

We have three different versions of an abstract and we would like you to read through them and decide a) what is the order of best to worst, and b) how would you improve the best one? You can do this task yourself or in a group. The key to this task is thinking about the comparison between the versions, so be sure to actively make notes on what made one version better than another. 

The aim of the abstract is to provide an overview of a whole article, so unlike the results comparison tasks, we do not have a task context section. If there is not enough context to understand what it is about, maybe that would be an evaluation point...

### Sections to compare

If it would help to make notes on a Word version, you can [download the three versions](Supporting/10_abstract_comparison.docx). 

#### Version 1 

#### Version 2 

#### Version 3 
