```{r, echo=FALSE}
source(file = "include/deadlines.R")
```

# Week 4

## Lab overview

Last week, you explored the introduction section as the first major part of a report. We wanted to cover what content goes into the introduction and report first to help orient you when you search for literature to include in your own reports. This week, we want to spend time on academic writing as a skill and process as its particularly relevant to the introduction and writing longer pieces of prose. 

There are three key components you will cover in the lab and resources this week: academic writing and paragraph structure, using evidence, and the use of generative AI. 

After reading the research skills chapter on academic writing, your pre-lab task is to attempt rewriting four extracts to shorten them and/or improve clarity and post your attempts to the Padlet board. The start of the lab will then discuss how you can approach rewriting the extracts and the editing process in general. The group element of the lab will then give you time to summarise your rationale, research question, and hypothesis, and discuss it with your lab leads. You will also have the opportunity to discuss how the content on academic writing could help you work on the stage one group report. 

## Tasks to complete prior to your lab

1. Read the [Academic Writing and Paragraph Structure](#academic-writing) research skills chapter. 

2. Read the sentences to edit and improve: 

    - A number of studies have originated a relationship between sleep and paranoia, so there is now a very clear and well-established relationship between sleep and paranoid thinking. The next research step will be to examine and identify by what method sleep and paranoid thinking are related (Reeve et al., 2015).

    - Research has shown that when visually inspecting faces that are rated as attractive, there is an increase in activity in the parts of the brain associated with processing rewards and pleasant things, than when viewing faces rated as being unattractive (Aharon et al., 2001).

    - It has been estimated that about 10% of people who are older than 65 and about fifty percent of people who are older than 85 years, have a diagnosis of a very serious condition termed Alzheimer’s Disease.
    
    - Research over the years has shown that there has been a huge increase in the number of anti-depressant prescriptions. Of all the medications on the market, anti-depressant prescriptions are the ones most commonly prescribed in the United States. 

3. Post your redrafts anonymously to the [Padlet board on the rewriting exercise](https://padlet.com/jebartlett94/rm1-week-4-rewriting-exercise-n60gg532j31fgdk2) under their respective columns. 

## Tasks to complete after attending your lab

1. Read through the [university position on AI and Student Learning Development materials](https://www.gla.ac.uk/myglasgow/sld/ai/) on guidance for students. 

2. Finalise your rationale, research question, and hypothesis (if applicable) in your group. 

## Next week 

In the final lab before reading week, we will explore the method section of a report. Method sections are largely standardised to contain several sub-sections you will see in most empirical quantitative articles, so we will break down the key content such as explaining who your participants are and what materials you used.

For the pre-lab reading, we have guidance on the structure and content of method sections. The pre-lab activities will involve sharing your group's research question and hypothesis (if applicable), and the lab will begin by exploring what each group is working on. 


